#!/usr/bin/env python3
"""Command line utility for analyzing and plotting player trajectories."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict

from mapsight.analysis import (
    PlayerTrajectory,
    compute_player_summary,
    get_player_trajectory,
    load_player_positions,
    plot_player_trajectory,
)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Analyze player position time series generated by build_empty_positions_index.py"
        )
    )
    parser.add_argument(
        "--positions",
        type=str,
        required=True,
        help=(
            "Path to the JSONL or Parquet file containing player position records "
            "(schemas/player_position.schema.json)"
        ),
    )
    parser.add_argument(
        "--player",
        type=str,
        required=True,
        help="Player identifier (matches player_uid; hyphens and case are ignored)",
    )
    parser.add_argument(
        "--team-id",
        type=str,
        default=None,
        help="Optional team identifier to disambiguate the player",
    )
    parser.add_argument(
        "--player-slot",
        type=str,
        default=None,
        help="Optional player slot (P1-P4) to disambiguate the player",
    )
    parser.add_argument(
        "--map-image",
        type=str,
        default=None,
        help="Optional path to a base minimap image for the visualization background",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Optional path where the plotted trajectory image will be saved",
    )
    parser.add_argument(
        "--use-pixel-coordinates",
        action="store_true",
        help="Plot using pixel coordinates instead of normalized coordinates",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display the trajectory plot interactively (requires GUI backend)",
    )
    parser.add_argument(
        "--summary-format",
        choices=["pretty", "json"],
        default="pretty",
        help="Output format for the textual summary",
    )
    return parser.parse_args()


def format_summary(summary: Dict[str, Any], *, output_format: str) -> str:
    if output_format == "json":
        return json.dumps(summary, indent=2)

    lines = [
        f"Player UID       : {summary['player_uid']}",
        f"Match ID         : {summary['match_id']}",
        f"Map Round        : {summary['map_round']}",
        f"Team ID          : {summary['team_id']}",
        f"Frames           : {summary['frames']}",
        f"Time Range (ms)  : {summary['start_timestamp_ms']} -> {summary['end_timestamp_ms']}",
        f"Duration (ms)    : {summary['duration_ms']}",
        f"Path Length (norm): {summary['normalized_path_length']:.4f}",
        f"Path Length (px) : {summary['pixel_path_length']:.2f}",
        "Status Counts   :",
    ]
    for status, count in summary["status_counts"].items():
        lines.append(f"  - {status}: {count}")
    return "\n".join(lines)


def main() -> None:
    arguments = parse_arguments()

    positions_dataframe = load_player_positions(arguments.positions)
    trajectory = get_player_trajectory(
        positions_dataframe,
        arguments.player,
        team_identifier=arguments.team_id,
        player_slot=arguments.player_slot,
    )

    summary = compute_player_summary(trajectory)
    print(format_summary(summary, output_format=arguments.summary_format))

    if arguments.output or arguments.show:
        plot_player_trajectory(
            trajectory,
            use_normalized_coordinates=not arguments.use_pixel_coordinates,
            map_image_path=arguments.map_image,
            output_path=arguments.output,
            show_figure=arguments.show,
        )
        if arguments.output:
            print(f"Saved trajectory plot to {Path(arguments.output).resolve()}")


if __name__ == "__main__":
    main()
